# Private routes
### Search a gym
GET http://localhost:3333/gyms/search?page=1&query=gym_title HTTP/1.1

### Get nearby gyms
GET http://localhost:3333/gyms/nearby?latitude=gym_latitude&longitude=gym_longitude HTTP/1.1

### Create a gym
POST http://localhost:3333/gyms HTTP/1.1
Host: localhost:3333
Content-Type: application/json

{
  "title": "Gym title",
  "description": "Gym description",
  "phone": "Gym phone",
  "latitude": "Gym latitude",
  "longitude": "gym longitude"
}
